import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Karla, Roboto, Poppins } from "next/font/google";
import ReactQueryProvider from "./components/ReactQueryProvider";
import { SearchProvider } from "../Context/SearchContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pokemon Explorer",
  description: "Generated by create next app",
};

export const karla = Karla({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-karla",
});

export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable} ${roboto.variable} ${poppins.variable} font-sans`}
      >
        <SearchProvider>
          <ReactQueryProvider>
            <Header />
            {children}
          </ReactQueryProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
